apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress-{{ .Values.env }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: hello-world-service-{{ .Values.env }}
                port:
                  number: {{ .Values.service.port }}
