apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-{{ .Values.env }}
  labels:
    app: hello-world
    environment: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: hello-world
